"""Compare the XSD 1.0 and XSD 1.1 forms of the vendor-extension proposal.

    py -3.12 compare_proposals.py

Both schemas are generated by make_proposal_xsd.py from the same published xmile-v1.0.xsd
and are meant to say the same thing: a vendor may add elements and attributes in its own
namespace, and nothing else. They differ only in what it costs to say it, which is the
question this script is here to answer:

  - how much of the schema each one has to touch;
  - whether they agree on real files;
  - what each one accepts that the other does not;
  - and what running the 1.1 version actually requires.

The last is not a footnote. libxml2 -- lxml, xmllint, nokogiri, PHP -- implements XSD 1.0
only, as do .NET's XmlSchemaSet and Java's default JAXP path. None of them can LOAD the
1.1 file; this script demonstrates that rather than asserting it. Reading it needs
Xerces-J with the v1.1 grammar requested explicitly, Saxon-EE, or the Python xmlschema
package (py -3.12 -m pip install xmlschema), which is what is used here.

Error counts are taken from one engine (xmlschema) across all three schemas, so the
columns are comparable. They are NOT comparable with the libxml2 counts that
check_proposal_xsd.py and validate_xmile.py report -- two validators legitimately
disagree about how many errors one broken element is worth.
"""
import glob
import os
import re
import sys

from lxml import etree

try:
    import xmlschema
except ImportError:
    sys.exit('this comparison needs an XSD 1.1 processor:\n'
             '    py -3.12 -m pip install xmlschema')

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))    # tools/v-generate/ -> repo root
OUT = os.path.join(REPO, 'proposals', 'schema')  # where generated schemas live
MODELS = os.path.join(REPO, 'models')            # the corpus to measure against
BASE = MODELS                                    # the corpus to measure against
XMILE = 'http://docs.oasis-open.org/xmile/ns/XMILE/v1.0'

PUBLISHED = os.path.join(HERE, 'xmile-v1.0.xsd')
PROP10 = os.path.join(OUT, 'xmile-v1.x-proposal.xsd')
PROPCT = os.path.join(OUT, 'xmile-v1.x-proposal-container.xsd')
PROP11 = os.path.join(OUT, 'xmile-v1.x-proposal-11.xsd')


def rule(title):
    print('\n%s\n%s' % (title, '-' * len(title)))


# --------------------------------------------------------------- 1. what it costs
rule('1. how much of the schema each version has to touch')

published = etree.parse(PUBLISHED)
prop10 = etree.parse(PROP10)
propct = etree.parse(PROPCT)
prop11 = etree.parse(PROP11)
XS = '{http://www.w3.org/2001/XMLSchema}'


def count(tree, tag):
    return len(tree.getroot().findall('.//%s%s' % (XS, tag)))


def body(tree):
    """Comment-free, indentation-free lines of a schema.

    Taken from the serialised TREE rather than the file on disk: both proposals have been
    through lxml, which normalises self-closing tags and whitespace, and diffing a
    reserialised file against the original would report hundreds of formatting-only lines
    as though they were the cost of the change.
    """
    text = etree.tostring(tree, encoding='unicode')
    text = re.sub(r'<!--.*?-->', '', text, flags=re.S)
    return [l.strip() for l in text.splitlines() if l.strip()]


def added_lines(a, b):
    """Lines in b that are not in a."""
    from difflib import unified_diff
    return sum(1 for l in unified_diff(body(a), body(b), n=0)
               if l.startswith('+') and not l.startswith('+++'))


TREES = (('published', published), ('1.0 wildcard', prop10),
         ('container', propct), ('XSD 1.1', prop11))
CLOSED = {'published': 'all', '1.0 wildcard': '27', 'container': '0', 'XSD 1.1': '0'}


def row(label, values):
    print('  %-30s %s' % (label, ''.join('%14s' % v for v in values)))


row('', [n for n, _ in TREES])
row('xs:any particles', [count(t, 'any') for _, t in TREES])
row('xs:anyAttribute particles', [count(t, 'anyAttribute') for _, t in TREES])
row('<extensions> refs', [len(t.getroot().findall('.//%selement[@ref="extensions"]' % XS))
                          for _, t in TREES])
row('lines added vs published',
    ['-'] + [added_lines(published, t) for _, t in TREES[1:]])
row('content models left closed', [CLOSED[n] for n, _ in TREES])

# --------------------------------------------------------- 2. the tooling penalty
rule('2. what it takes to run each one')

for label, path in (('1.0 wildcard', PROP10), ('container', PROPCT), ('XSD 1.1', PROP11)):
    try:
        etree.XMLSchema(etree.parse(path))
        print('  libxml2      %-14s loads and compiles' % label)
    except etree.XMLSchemaParseError as exc:
        first = str(exc).splitlines()[0]
        print('  libxml2      %-14s CANNOT LOAD' % label)
        print('               %s' % first[:150])

s_pub = xmlschema.XMLSchema10(PUBLISHED)
s10 = xmlschema.XMLSchema10(PROP10)
sct = xmlschema.XMLSchema10(PROPCT)
s11 = xmlschema.XMLSchema11(PROP11)
print('  xmlschema    all three      load and compile')

# ------------------------------------------------------------- 3. agreement on files
rule('3. what the corpus actually contains')

# The census, not the error count, is the honest measure of reach -- see section 4.
# An "attachment point" is a vendor element whose parent is a standard XMILE element.
# Vendor elements nested inside other vendor elements are already isolated and no schema
# change affects them.
ALL_PARENTS = set()
for ct in published.getroot().iter(XS + 'complexType'):
    if ct.find(XS + 'all') is None:
        continue
    p = ct
    while p is not None:
        if p.tag == XS + 'element' and p.get('name'):
            ALL_PARENTS.add(p.get('name'))
            break
        p = p.getparent()


def nsof(tag):
    return tag[1:tag.index('}')] if isinstance(tag, str) and tag.startswith('{') else ''


def lname(tag):
    return tag.rsplit('}', 1)[-1]


files = sorted(glob.glob(BASE + '/**/*.xmile', recursive=True) +
               glob.glob(BASE + '/**/*.stmx', recursive=True))
docs = []
for f in files:
    try:
        docs.append((f, etree.parse(f)))
    except Exception:                             # noqa: BLE001 - not well-formed
        pass

vendor_total = nested = anchored_open = anchored_all = 0
vendor_attrs = 0
for _, doc in docs:
    for el in doc.iter():
        if not isinstance(el.tag, str):
            continue
        vendor_attrs += sum(1 for k in el.attrib
                            if k.startswith('{') and 'XMLSchema-instance' not in k)
        if not nsof(el.tag) or nsof(el.tag) == XMILE:
            continue
        vendor_total += 1
        p = el.getparent()
        if p is not None and isinstance(p.tag, str) and nsof(p.tag) \
                and nsof(p.tag) != XMILE:
            nested += 1
        elif p is not None and lname(p.tag) in ALL_PARENTS:
            anchored_all += 1
        else:
            anchored_open += 1

anchored = anchored_open + anchored_all
print('  %d files, %d vendor elements, %d vendor attributes' %
      (len(docs), vendor_total, vendor_attrs))
print('    already nested inside another vendor element  %6d  (%.0f%%)'
      % (nested, 100 * nested / vendor_total))
print('    attached to a standard XMILE element          %6d  (%.0f%%)'
      % (anchored, 100 * anchored / vendor_total))
print('        parent is choice/sequence                 %6d' % anchored_open)
print('        parent is xs:all                          %6d' % anchored_all)

print('\n  vendor elements each proposal admits, of the %d attachment points:' % anchored)
print('    1.0 wildcard   %5d  (%3.0f%%)  in place, files unchanged'
      % (anchored_open, 100 * anchored_open / anchored))
print('    container      %5d  (%3.0f%%)  but %d of them only after being moved'
      % (anchored, 100, anchored_all))
print('                          %s inside <extensions>' % (' ' * 14))
print('    XSD 1.1        %5d  (%3.0f%%)  in place, files unchanged'
      % (anchored, 100))

rule('4. error counts, and why they mislead')

totals = {}
for name, schema in (('published', s_pub), ('1.0 wildcard', s10),
                     ('container', sct), ('XSD 1.1', s11)):
    totals[name] = sum(len(list(schema.iter_errors(doc))) for _, doc in docs)
    print('  %-14s %6d errors' % (name, totals[name]))

# One file makes the point better than the totals do: validation stops descending once a
# parent's content model fails, so a single bad element near the top of a file masks
# every vendor element below it.
worst = None
for f, doc in docs:
    n = sum(1 for e in doc.iter()
            if isinstance(e.tag, str) and nsof(e.tag) and nsof(e.tag) != XMILE
            and e.getparent() is not None and isinstance(e.getparent().tag, str)
            and lname(e.getparent().tag) in ALL_PARENTS)
    if worst is None or n > worst[1]:
        worst = (f, n, doc)
f, n, doc = worst
print('\n  %s' % os.path.relpath(f, BASE))
print('    vendor elements in xs:all parents  %4d' % n)
print('    errors from the 1.0 wildcard schema %4d' % len(list(s10.iter_errors(doc))))
print('    -- the count is not a measure of how much content is blocked. Section 3 is.')

# ------------------------------------------------------- 4. what only 1.1 can do
rule('5. the cases that separate them')

HDR = ('<header><vendor>Ventana Systems</vendor><product version="1.0">Vensim</product>'
       '<name>t</name></header>')


def doc(body, header=HDR):
    return ('<xmile version="1.0" xmlns="%s" '
            'xmlns:vensim="http://www.vensim.com/XMILE" '
            'xmlns:isee="http://iseesystems.com/XMILE">%s'
            '<model><variables>%s</variables></model></xmile>'
            % (XMILE, header, body)).encode()


CASES = [
    # (label, document, expected under 1.0 / container / 1.1)
    ('vendor element in a <stock> (xs:choice)',
     doc('<stock name="S"><eqn>0</eqn><vensim:netflow>x</vensim:netflow></stock>'),
     True, True, True),
    ('vendor attribute on a <stock>',
     doc('<stock name="S" isee:varattrib="data"><eqn>0</eqn></stock>'),
     True, True, True),
    ('vendor element in <header> (xs:all), in place',
     doc('<stock name="S"><eqn>0</eqn></stock>',
         header='<header><vendor>V</vendor><vensim:origin>x</vensim:origin></header>'),
     False, False, True),
    # The 1.1 column here is not a failure but the finding: <extensions> is in the XMILE
    # namespace, and a defaultOpenContent wildcard admits ##other only. A file written
    # for the container schema does NOT validate against the 1.1 one. The two are not
    # interchangeable, so a container adopted now would have to be carried forward into
    # any later move to 1.1 rather than retired by it.
    ('... the same, inside <extensions>',
     doc('<stock name="S"><eqn>0</eqn></stock>',
         header='<header><vendor>V</vendor>'
                '<extensions><vensim:origin>x</vensim:origin></extensions></header>'),
     False, True, False),
    # <view> extends view_content_type, a repeating xs:choice, so the plain wildcard
    # reaches it through the base type. 359 vendor elements in the corpus hang here.
    ('vendor element in a <view> (inherited xs:choice)',
     doc('<stock name="S"><eqn>0</eqn></stock>').replace(
         b'</model>', b'<views><view><isee:annotation/></view></views></model>'),
     True, True, True),
    ('vendor attribute on <header> (xs:all)',
     doc('<stock name="S"><eqn>0</eqn></stock>',
         header='<header isee:draw_as="x"><vendor>V</vendor></header>'),
     True, True, True),
    ('REJECT unprefixed unknown element',
     doc('<stock name="S"><eqn>0</eqn><bonkerstag>x</bonkerstag></stock>'),
     False, False, False),
    ('REJECT the same inside <extensions>',
     doc('<stock name="S"><eqn>0</eqn></stock>',
         header='<header><vendor>V</vendor>'
                '<extensions><bonkerstag>x</bonkerstag></extensions></header>'),
     False, False, False),
    ('REJECT unprefixed unknown attribute',
     doc('<stock name="S" foreignattribute="nonsense"><eqn>0</eqn></stock>'),
     False, False, False),
    ('REJECT vendor element in the XMILE namespace',
     doc('<stock name="S"><eqn>0</eqn><netflow>x</netflow></stock>'),
     False, False, False),
]

print('  %-46s%14s%14s%14s' % ('', '1.0 wildcard', 'container', 'XSD 1.1'))
bad = 0
for label, src, w10, wct, w11 in CASES:
    d = etree.fromstring(src)
    got = (s10.is_valid(d), sct.is_valid(d), s11.is_valid(d))
    ok = got == (w10, wct, w11)
    bad += not ok
    print('  %-46s%s%s' % (label,
                           ''.join('%14s' % ('accepted' if g else 'rejected')
                                   for g in got),
                           '' if ok else '   <-- expected %s' % ((w10, wct, w11),)))

print('\n%s' % ('all cases as expected' if not bad else '%d CASE(S) UNEXPECTED' % bad))
sys.exit(1 if bad else 0)
